/**
 * Exercise guide data containing performance details for each exercise.
 * This data is displayed in the Guide component when users want to learn
 * how to perform an exercise properly.
 */

export type ExerciseGuide = {
  id: string;
  name: string;
  holdTime: string;
  reps: string;
  frequency: string;
  howTo: string[];
  tips: string[];
};

export const EXERCISE_GUIDES: Record<string, ExerciseGuide> = {
  cps: {
    id: "cps",
    name: "CPS (Correct Tongue Posture)",
    holdTime: "5-10 seconds per position",
    reps: "10-15 reps",
    frequency: "2-3 times daily",
    howTo: [
      "Close your mouth and place your tongue on the roof of your mouth",
      "Seal your lips and puff both cheeks evenly with air",
      "Keep your jaw relaxed while maintaining the cheek puff",
      "Slowly pucker your lips forward into a small 'O' without letting air escape",
      "Hold the position, feeling the engagement through your cheeks and lips",
    ],
    tips: [
      "Keep your jaw relaxed throughout — don't clench",
      "The air should stay sealed in your cheeks without leaking",
      "Focus on controlled lip engagement while holding the puff",
    ],
  },
  "thumb-pulling": {
    id: "thumb-pulling",
    name: "Thumb Pulling",
    holdTime: "10-15 seconds per rep",
    reps: "10-15 reps",
    frequency: "2-3 times daily",
    howTo: [
      "Wash your hands thoroughly",
      "Place your thumbs inside your mouth at the corners, with fingers resting outside on your cheeks",
      "Keep your lips closed around your thumbs",
      "Gently pull outward at the mouth corners while keeping lips sealed and jaw relaxed",
      "While holding the pull, try to smile to stretch the cheek and mouth-corner area",
    ],
    tips: [
      "Use gentle, steady outward pressure — never force",
      "Keep your jaw relaxed throughout the stretch",
      "This targets the muscles around the mouth corners and cheeks",
    ],
  },
  "chin-tucks": {
    id: "chin-tucks",
    name: "Chin Tucks",
    holdTime: "5-10 seconds (work up to 15-20 sec)",
    reps: "10-20 reps per session",
    frequency: "2-5 times per day",
    howTo: [
      "Sit or stand tall with good posture",
      "Keep your eyes looking straight ahead",
      "Pull your chin straight back (like making a double chin)",
      "Don't tilt your head up or down",
      "Hold, then return to neutral position",
    ],
    tips: [
      "Imagine a string pulling the back of your head up",
      "Keep shoulders relaxed and down",
      "Start with fewer reps and build up gradually",
    ],
  },
  "hunter-eyes": {
    id: "hunter-eyes",
    name: "Hunter Eyes 1",
    holdTime: "5 seconds per position",
    reps: "10-15 reps",
    frequency: "2 sets daily",
    howTo: [
      "Relax your face completely",
      "Place your index fingers at the outer corners of your eyes",
      "Gently lift and hold the skin while focusing your gaze straight forward",
      "Maintain a slight, controlled squint with your lower eyelids",
      "Close your eyes, move fingers to the outer brow/temple area, and hold a soft squint",
    ],
    tips: [
      "Keep your forehead smooth — don't wrinkle or raise your brows",
      "The squint should come from the lower eyelids, not the forehead",
      "Use gentle finger pressure to support the eye area, not to pull",
    ],
  },
  "hyoid-stretch": {
    id: "hyoid-stretch",
    name: "Hyoid Stretch",
    holdTime: "10-15 seconds per position",
    reps: "3-5 full cycles (back, neutral, down)",
    frequency: "2-3 times daily",
    howTo: [
      "Stand or sit with good posture, shoulders relaxed",
      "Cross your hands over your upper chest just below the collarbone",
      "Tilt your head back to look up, feeling the front of your neck lengthen",
      "Slowly return your head to neutral position with your chin level",
      "Then tuck your chin down toward your chest to stretch the back of the neck",
    ],
    tips: [
      "Keep your hands firmly on your chest to anchor the stretch",
      "Move slowly through each position — don't jerk your head",
      "You should feel a gentle stretch in the front, then back of your neck",
    ],
  },
  "lymphatic-drainage": {
    id: "lymphatic-drainage",
    name: "Lymphatic Drainage",
    holdTime: "3-5 minutes per session",
    reps: "10-15 strokes per area",
    frequency: "Daily, ideally at night",
    howTo: [
      "Make a loose fist and place your knuckles under your chin",
      "Sweep firmly along the jawline from chin toward your ears in an upward motion",
      "Repeat several times on each side of the jaw",
      "Then use your fingertips to gently stroke down the side of your neck",
      "Finish by stroking down toward the collarbone with light pressure",
    ],
    tips: [
      "Use firm but comfortable pressure along the jawline",
      "Always sweep upward along the jaw, then downward along the neck",
      "Apply facial oil or moisturizer for a smoother glide",
    ],
  },
  "upward-chewing": {
    id: "upward-chewing",
    name: "Upward Chewing",
    holdTime: "2-3 seconds per chew",
    reps: "15-20 chews per set, 3 sets",
    frequency: "Daily",
    howTo: [
      "Sit or stand with good posture and a tall neck",
      "Tilt your head slightly upward, keeping your neck long",
      "Start with your lips closed and jaw relaxed",
      "Slowly open your mouth wide in a controlled chewing motion",
      "Close and repeat in a slow, rhythmic pattern while keeping your head tilted up",
    ],
    tips: [
      "Keep the movement slow and controlled — don't rush",
      "Focus on engaging the jaw and under-chin muscles",
      "Tilt your head just slightly — don't strain your neck",
    ],
  },
  "neck-lift": {
    id: "neck-lift",
    name: "Neck Lift",
    holdTime: "5-10 seconds",
    reps: "10-20 reps",
    frequency: "Daily",
    howTo: [
      "Keep shoulders relaxed and down",
      "Tilt your head back slightly",
      "Thrust your jaw forward",
      "Feel the stretch under your chin and neck",
      "Hold, then return to neutral",
    ],
    tips: [
      "Don't tilt back too far - keep it comfortable",
      "Feel the front of your neck engage",
      "Combine with deep breathing for better results",
    ],
  },
  "jaw-resistance": {
    id: "jaw-resistance",
    name: "Jaw Resistance",
    holdTime: "5-10 seconds per rep",
    reps: "3 sets of 10 reps",
    frequency: "Daily",
    howTo: [
      "Make a fist and place it under your chin",
      "Try to open your mouth while resisting with your fist",
      "Push against the resistance for the full hold",
      "Release and relax",
      "Repeat with controlled, steady pressure",
    ],
    tips: [
      "Start with light resistance and build up",
      "Don't strain or clench too hard",
      "Keep the rest of your face relaxed",
    ],
  },
  "eyes-and-cheeks": {
    id: "eyes-and-cheeks",
    name: "Eyes and Cheeks",
    holdTime: "10-15 seconds per position",
    reps: "5-10 reps",
    frequency: "Daily",
    howTo: [
      "Start with your face fully relaxed and shoulders dropped down",
      "Close your eyes gently and release all facial tension",
      "Keep your shoulders relaxed and away from your ears",
      "Open your eyes and slowly drop your jaw open as wide as comfortable",
      "Hold the wide mouth position without scrunching or tensing your face",
    ],
    tips: [
      "Focus on keeping shoulders down throughout the exercise",
      "The jaw drop should feel natural, not forced",
      "This exercise helps release tension in both the eye and cheek area",
    ],
  },
  "alternating-cheek-puffs": {
    id: "alternating-cheek-puffs",
    name: "Alternating Cheek Puffs",
    holdTime: "3-5 seconds each side",
    reps: "10-15 alternations per set",
    frequency: "3-5 sets daily",
    howTo: [
      "Seal your lips completely",
      "Fill your mouth with air",
      "Push all the air into one cheek",
      "Hold for 3-5 seconds",
      "Move the air to the opposite cheek and hold",
    ],
    tips: [
      "Keep lips tightly sealed throughout",
      "Don't let any air escape",
      "Start slowly and increase speed as you improve",
    ],
  },
  "nose-massage": {
    id: "nose-massage",
    name: "Nose Massage",
    holdTime: "5 minutes total",
    reps: "10 reps for nose push exercise",
    frequency: "Daily",
    howTo: [
      "Apply a small amount of facial oil to your nose",
      "Use fingertips to massage the bridge in circular motions",
      "Move down to the sides of the nose",
      "For nose push: push tip up with index finger",
      "Push tip down 10 times with gentle resistance",
    ],
    tips: [
      "Use gentle, consistent pressure",
      "Focus on circulation, not reshaping",
      "This helps with muscle tone around the nose",
    ],
  },
  "sternocleidomastoid-stretch": {
    id: "sternocleidomastoid-stretch",
    name: "SCM Stretch",
    holdTime: "15-30 seconds each side",
    reps: "3-5 reps per side",
    frequency: "Daily",
    howTo: [
      "Place one hand on the side of your neck",
      "Turn your head slightly away from that hand",
      "Puff your cheeks with air while holding the stretch",
      "Feel the stretch along the neck muscle",
      "Switch sides and repeat",
    ],
    tips: [
      "Don't force the stretch - keep it gentle",
      "Breathe normally throughout",
      "Great for neck tension relief",
    ],
  },
  "nose-tongue-touch": {
    id: "nose-tongue-touch",
    name: "Nose Touching with Tongue",
    holdTime: "10 seconds",
    reps: "5-10 reps with 10-second breaks",
    frequency: "Daily",
    howTo: [
      "Keep your head straight, facing forward",
      "Stick your tongue out",
      "Stretch your tongue upward toward your nose",
      "Reach as high as possible without straining",
      "Hold at maximum extension, then relax",
    ],
    tips: [
      "Don't strain - stretch only as far as comfortable",
      "Keep your jaw and face relaxed",
      "This exercises the tongue and maxilla area",
    ],
  },
  "fish-face": {
    id: "fish-face",
    name: "Fish Face",
    holdTime: "15-30 seconds (work up to 60-90 sec)",
    reps: "5-10 reps",
    frequency: "Daily",
    howTo: [
      "Start with lips closed, face relaxed",
      "Suck your cheeks inward toward your teeth",
      "Pucker your lips slightly (fish face)",
      "Try to smile while holding the position",
      "Hold, then release slowly",
    ],
    tips: [
      "Feel the cheek muscles working",
      "Keep breathing normally through your nose",
      "Great for cheekbone definition and reducing face fat",
    ],
  },
  "cheekbone-knuckle-massage": {
    id: "cheekbone-knuckle-massage",
    name: "Cheekbone Knuckle Massage",
    holdTime: "30-60 seconds continuous",
    reps: "10-15 strokes per side",
    frequency: "Daily",
    howTo: [
      "Curl your fingers into a loose fist on both hands",
      "Place the flat of your knuckles beside your nose at cheekbone level",
      "Apply firm but comfortable pressure against the cheekbones",
      "Sweep outward along the cheekbones from nose toward ears",
      "Repeat in smooth, continuous upward strokes",
    ],
    tips: [
      "Use firm pressure but never painful — skin should move with the knuckles",
      "Always stroke outward (nose to ears), never inward",
      "Apply facial oil or moisturizer for smoother glide",
    ],
  },
  "neck-curls": {
    id: "neck-curls",
    name: "Neck Curls",
    holdTime: "2-3 seconds per rep",
    reps: "2 sets of 10 reps",
    frequency: "Twice a week (max)",
    howTo: [
      "Lay on your back with your head hanging off the edge of a bed or bench",
      "Press your tongue firmly against the roof of your mouth (mewing position)",
      "Curl your chin toward your chest, creating as many double chins as possible",
      "Focus on contracting the area under your chin (superhyoid), not your neck fibers",
      "Slowly extend your head back, pulling your chin as far back as possible, then repeat",
    ],
    tips: [
      "Warm up thoroughly before starting — these muscles are often underdeveloped",
      "Do NOT curl your neck up like a sit-up; focus specifically on the under-chin squeeze",
      "Keep tongue on the roof of your mouth throughout the entire movement",
    ],
  },
  "resisted-jaw-openings": {
    id: "resisted-jaw-openings",
    name: "Resisted Jaw Openings",
    holdTime: "2-3 seconds per rep",
    reps: "2 sets of 20 reps (beginners), up to 5-6 sets (advanced)",
    frequency: "Twice a week",
    howTo: [
      "Bring your hands together as if praying",
      "Create a 90-degree angle between your thumbs and index fingers",
      "Place thumbs underneath your chin, index fingers against your nose for stability",
      "Keep your head up and body straight",
      "Slowly open your jaw against the resistance of your thumbs, squeezing the superhyoid muscles",
    ],
    tips: [
      "Go very easy at first to avoid TMJ problems",
      "For warm-up sets, apply only light pressure; increase for working sets",
      "Do this exercise on the same day as neck curls, either before or after",
    ],
  },
  "chin-tucks-with-head-tilt": {
    id: "chin-tucks-with-head-tilt",
    name: "Chin Tucks with Head Tilt",
    holdTime: "10 seconds per rep",
    reps: "15 reps, 3 sets",
    frequency: "Daily",
    howTo: [
      "Stand or sit with spine straight and shoulders back",
      "Identify your overdeveloped (stronger/bigger) side",
      "Tilt your head AWAY from the strong side (toward the weak side) about 15-20 degrees",
      "While tilted, pull your chin straight back (not down) to create a double chin",
      "Hold for 10 seconds, feeling the neck stretch, then release",
    ],
    tips: [
      "Only tilt 15-20 degrees — don't overdo the angle",
      "The chin goes straight BACK, never down — imagine pushing into a wall behind you",
      "This variation specifically targets facial asymmetry by balancing neck muscles",
    ],
  },

  // ── Skincare protocols ────────────────────────────────────────────────────

  "cold-water-splash": {
    id: "cold-water-splash",
    name: "Cold Water Splash",
    holdTime: "30 seconds",
    reps: "3–5 splashes",
    frequency: "Every morning",
    howTo: [
      "Fill your sink with cold water — add a few ice cubes if available",
      "Splash cold water directly onto your face 3–5 times",
      "Pat dry gently with a clean towel — do not rub",
      "Follow immediately with your morning moisturiser to lock in hydration",
    ],
    tips: [
      "The colder the water the better — it constricts blood vessels and tightens the skin",
      "Do this before any other morning skincare to reset inflammation overnight",
      "Consistency matters more than intensity — daily is the goal",
    ],
  },
  "gua-sha": {
    id: "gua-sha",
    name: "Gua Sha Massage",
    holdTime: "3–5 minutes total",
    reps: "5–10 strokes per area",
    frequency: "Daily, preferably morning",
    howTo: [
      "Apply a few drops of facial oil to your skin for smooth glide",
      "Hold the gua sha tool at a 15-degree angle to your face",
      "Starting from the centre of the chin, stroke outward along the jawline toward your ear",
      "Move up to the cheekbone — sweep from nose outward toward the ear with firm, consistent pressure",
      "Finish by gently stroking down the sides of the neck to drain the lymph nodes",
    ],
    tips: [
      "Always stroke upward and outward — never drag downward on the face",
      "Use firm but comfortable pressure; you should not feel pain",
      "Morning is ideal: it clears overnight fluid retention for an immediately sharper look",
    ],
  },
  "facial-icing": {
    id: "facial-icing",
    name: "Facial Icing",
    holdTime: "15–30 seconds per area",
    reps: "2–3 passes per area",
    frequency: "Daily, especially after breakouts",
    howTo: [
      "Wrap an ice cube in a thin cloth or use an ice roller",
      "Starting at the centre of the forehead, glide outward in slow strokes",
      "Move to the cheeks — sweep from nose toward ears",
      "Press and hold on any active spots for 15–20 seconds to reduce inflammation",
      "Finish with upward strokes along the jawline and neck",
    ],
    tips: [
      "Never apply bare ice directly to skin — always wrap it",
      "Do not stay in one spot longer than 30 seconds to avoid skin damage",
      "Use after a breakout to reduce redness overnight — results are visible by morning",
    ],
  },
  "oil-cleanser": {
    id: "oil-cleanser",
    name: "Oil-Based Cleanser",
    holdTime: "60 seconds massage time",
    reps: "1 full cleanse",
    frequency: "Every evening",
    howTo: [
      "Apply a coin-sized amount of oil cleanser to dry hands — do not wet your face first",
      "Massage gently into your face in circular motions for a full 60 seconds",
      "Pay extra attention to the nose, chin, and forehead where sebum accumulates",
      "Wet your hands and emulsify the oil — it will turn milky",
      "Rinse thoroughly with lukewarm water, then follow with a water-based cleanser",
    ],
    tips: [
      "Oil dissolves oil — this removes sunscreen, sebum, and pollution that water-based cleansers miss",
      "The 60-second massage is non-negotiable — rushing reduces effectiveness significantly",
      "Follow with a gentle water-based cleanser for a full double cleanse",
    ],
  },
  "bentonite-clay-mask": {
    id: "bentonite-clay-mask",
    name: "Bentonite Clay Mask",
    holdTime: "10–15 minutes",
    reps: "1 mask application",
    frequency: "1–2 times per week",
    howTo: [
      "Mix bentonite clay powder with equal parts apple cider vinegar or water to form a smooth paste",
      "Apply a thin, even layer to clean skin — avoid the eye and lip area",
      "Leave on for 10–15 minutes; the clay will lighten as it dries",
      "Rinse off with warm water using circular motions to lightly exfoliate",
      "Follow immediately with moisturiser — clay is intensely drying",
    ],
    tips: [
      "Use apple cider vinegar instead of water to activate the clay's drawing power",
      "Do not leave on past 15 minutes — over-drying irritates the skin barrier",
      "Use only 1–2x per week; overuse strips the skin and worsens breakouts",
    ],
  },
  "turmeric-mask": {
    id: "turmeric-mask",
    name: "Turmeric Mask",
    holdTime: "15–20 minutes",
    reps: "1 mask application",
    frequency: "1–2 times per week",
    howTo: [
      "Mix half a teaspoon of turmeric powder with one teaspoon of raw honey",
      "Add one teaspoon of plain full-fat yogurt and stir into a smooth paste",
      "Apply an even layer to clean skin using your fingers or a brush",
      "Leave on for 15–20 minutes — the yogurt enzymes work best when given time",
      "Rinse off with cool water and gently massage in circular motions",
    ],
    tips: [
      "Turmeric stains — use an old towel and avoid contact with fabric",
      "The lactic acid in yogurt gently exfoliates and brightens on its own",
      "Honey is antibacterial and moisturising — do not substitute with processed honey",
    ],
  },

  // ── Lifestyle protocols ───────────────────────────────────────────────────

  "sprint-session": {
    id: "sprint-session",
    name: "Sprint Session",
    holdTime: "10–20 seconds per sprint",
    reps: "6–10 sprints",
    frequency: "3–4 times per week",
    howTo: [
      "Warm up with 5 minutes of light jogging or dynamic stretches",
      "Sprint at maximum effort for 10–20 seconds",
      "Rest fully for 60–90 seconds — full recovery between sprints is key",
      "Repeat for 6–10 rounds depending on fitness level",
      "Cool down with 5 minutes of walking and static stretching",
    ],
    tips: [
      "True sprinting — not fast jogging — is what drives the hormonal response",
      "Outdoor sprinting on grass is ideal; treadmill at max incline works as a substitute",
      "The testosterone and HGH spike from sprints is measurable for hours after",
    ],
  },
  "nasal-breathing": {
    id: "nasal-breathing",
    name: "Nasal Breathing Practice",
    holdTime: "Throughout the day",
    reps: "Continuous habit",
    frequency: "All day, every day",
    howTo: [
      "Set an hourly reminder to check your breathing pattern",
      "At each check: close your mouth and breathe slowly through your nose",
      "During exercise: keep your mouth closed for as long as comfortable",
      "At night: use mouth tape if you know you breathe through your mouth while sleeping",
      "Practice box breathing (4 in, 4 hold, 4 out, 4 hold) for 5 minutes each morning",
    ],
    tips: [
      "The single hardest and most impactful habit in facial structure development",
      "Mouth breathing during sleep undoes hours of daytime habit — address it directly",
      "Results in palate width and jaw structure take months but are structural and permanent",
    ],
  },
  "cold-shower": {
    id: "cold-shower",
    name: "Cold Shower",
    holdTime: "2–5 minutes cold exposure",
    reps: "1 session",
    frequency: "Daily, preferably morning",
    howTo: [
      "Take your normal shower first",
      "In the final 2–5 minutes, switch the water to the coldest setting",
      "Focus cold water on the face and neck for maximum vasoconstriction",
      "Control your breathing — slow exhales calm the cold shock response",
      "End on cold — do not switch back to warm water",
    ],
    tips: [
      "Start with 30 seconds cold and build up over 2 weeks",
      "The face benefits specifically from vasoconstriction — tighter skin, less puffiness",
      "Cold exposure in the morning also spikes norepinephrine, improving mood and drive",
    ],
  },
  "sunlight-exposure": {
    id: "sunlight-exposure",
    name: "10-Min Morning Sunlight",
    holdTime: "10 minutes minimum",
    reps: "1 session",
    frequency: "Every morning within 1 hour of waking",
    howTo: [
      "Within the first hour of waking, go outside — do not look through glass",
      "Face the direction of the sun without looking directly at it",
      "Allow sunlight to hit your face and eyes (eyelids open) for at least 10 minutes",
      "Combine with a walk or cold water to stack habits efficiently",
    ],
    tips: [
      "This is about circadian rhythm, not just vitamin D — the full-spectrum light signal is what matters",
      "Cloudy days still work — go outside anyway; light intensity is still 10x that of indoor lighting",
      "Within 1 hour of waking is critical — it sets your cortisol peak at the right time",
    ],
  },
  "mewing": {
    id: "mewing",
    name: "Mewing (Tongue Posture)",
    holdTime: "Continuous throughout the day",
    reps: "Resting habit",
    frequency: "All waking hours",
    howTo: [
      "Close your lips gently with teeth lightly touching or slightly apart",
      "Place the entire tongue flat against the roof of your mouth — not just the tip",
      "Ensure the back of the tongue is also touching the palate",
      "Swallow naturally — the tongue should seal the palate during each swallow",
      "Check your posture: head up, neck straight, shoulders back",
    ],
    tips: [
      "The back-third of the tongue contact is what most people miss — focus on it",
      "Set hourly reminders until it becomes unconscious; this takes 2–4 weeks",
      "Results are structural and long-term — do not expect visible change before 6+ months",
    ],
  },
  "back-sleeping": {
    id: "back-sleeping",
    name: "Sleep on Your Back Tonight",
    holdTime: "Full night",
    reps: "1 full sleep cycle",
    frequency: "Every night",
    howTo: [
      "Use a single, low-profile pillow to keep your head and neck aligned",
      "Place a pillow under your knees to reduce lower back strain and improve comfort",
      "If you tend to roll over: place a body pillow on either side of you",
      "Use a silk or satin pillowcase — it reduces friction if you do shift positions",
    ],
    tips: [
      "Side sleeping compresses one side of the face for 6–8 hours every night — asymmetry compounds over years",
      "Most people shift position during sleep; the goal is to start and return to your back",
      "Cervical neck pillows specifically designed for back sleepers help train the habit",
    ],
  },

  // ── Dietary protocols ─────────────────────────────────────────────────────

  "lemon-electrolytes": {
    id: "lemon-electrolytes",
    name: "Lemon + Electrolytes",
    holdTime: "Drink within 30 min of waking",
    reps: "1 large glass (400–500ml)",
    frequency: "Every morning",
    howTo: [
      "Fill a large glass with room temperature or slightly warm water",
      "Squeeze half a fresh lemon — do not use bottled lemon juice",
      "Add a small pinch of high-quality salt (pink Himalayan or sea salt)",
      "Optional: add a small amount of raw honey or coconut water for potassium",
      "Drink slowly over 10–15 minutes on an empty stomach",
    ],
    tips: [
      "The salt replaces electrolytes lost overnight and triggers kidney flush of retained water",
      "Lemon alkalises the body's pH despite being acidic — this reduces inflammation systemically",
      "Drink through a straw to protect tooth enamel from citric acid",
    ],
  },
  "egg-yolk-banana": {
    id: "egg-yolk-banana",
    name: "Egg Yolks + Banana",
    holdTime: "Consume within 1 hour of waking",
    reps: "2–4 egg yolks + 1 banana",
    frequency: "Daily or most mornings",
    howTo: [
      "Soft-boil or poach 2–4 eggs — avoid overcooking yolks; runny preserves nutrients",
      "Eat the yolks — white is optional but yolks are the target here",
      "Eat one ripe banana alongside — not raw banana, a ripe one for this meal",
      "Eat together as a complete meal or alongside other whole foods",
    ],
    tips: [
      "Egg yolks are one of the most complete nutrient sources: choline, B2, B12, D, K2, selenium",
      "Cholesterol in yolks is a direct precursor to testosterone — do not fear it",
      "Potassium from banana + sodium from salt water = optimal cellular hydration for depuffing the face",
    ],
  },
  "black-raisins": {
    id: "black-raisins",
    name: "Black Raisins (soaked overnight)",
    holdTime: "Eat first thing in the morning",
    reps: "Small handful (20–30 raisins)",
    frequency: "Daily",
    howTo: [
      "The night before: place a small handful of black raisins in a glass of water",
      "Leave to soak overnight at room temperature",
      "In the morning: drain and eat the soaked raisins on an empty stomach",
      "Drink the soaking water too — it contains water-soluble nutrients that leached out",
    ],
    tips: [
      "Soaking increases bioavailability of iron and antioxidants significantly",
      "Black raisins (not golden) contain higher anthocyanin content — the active compound",
      "Eat before any caffeinated drink — caffeine inhibits iron absorption",
    ],
  },
  "raw-banana": {
    id: "raw-banana",
    name: "Raw (Unripe) Banana",
    holdTime: "Anytime in the morning",
    reps: "1 medium unripe banana",
    frequency: "Daily or most days",
    howTo: [
      "Select a banana that is still green-yellow — not fully ripe",
      "Eat it plain or slice it into yogurt or oats",
      "It will taste starchy and less sweet than a ripe banana — that is correct",
      "Follow with plenty of water to help the resistant starch work effectively",
    ],
    tips: [
      "Resistant starch in unripe bananas feeds beneficial gut bacteria — this is the mechanism for reduced inflammation",
      "Gut health and skin quality are directly linked; improving one improves the other",
      "If the texture is unpleasant, blend it into a smoothie with other ingredients",
    ],
  },
  "beef-liver": {
    id: "beef-liver",
    name: "Beef Liver",
    holdTime: "Consume 1–3x per week",
    reps: "100–150g per serving",
    frequency: "2–3 times per week",
    howTo: [
      "Source grass-fed beef liver from a quality butcher where possible",
      "Slice thin — about 1cm thick — for even, fast cooking",
      "Pan-fry on high heat with butter for 2–3 minutes per side — do not overcook",
      "Season simply with salt, pepper, and lemon juice",
      "Alternatively: freeze and grate small amounts raw into smoothies to mask the taste",
    ],
    tips: [
      "Liver is the single most nutrient-dense food on earth — gram for gram it beats every other food",
      "Vitamin A in liver (retinol form) directly regulates skin cell turnover and sebum production",
      "Do not exceed 150g per serving — vitamin A can accumulate; 2–3x per week is optimal",
    ],
  },
  "red-meat": {
    id: "red-meat",
    name: "Red Meat (unprocessed)",
    holdTime: "Dinner time",
    reps: "150–250g per serving",
    frequency: "3–5 times per week",
    howTo: [
      "Choose unprocessed cuts: ribeye, sirloin, ground beef, or lamb — avoid processed meats",
      "Cook to medium or medium-rare for optimal nutrient retention",
      "Season simply — salt, pepper, herbs; avoid heavy sauces that add inflammation",
      "Pair with vegetables rich in vitamin C (bell peppers, broccoli) to maximise iron absorption",
    ],
    tips: [
      "Zinc in red meat is the most bioavailable form — it directly supports testosterone and collagen synthesis",
      "Carnitine in beef improves fat metabolism which contributes to facial leanness over time",
      "Grain-fed is fine; grass-fed has higher omega-3 content but both are excellent sources of the key minerals",
    ],
  },
  "unsalted-cheese": {
    id: "unsalted-cheese",
    name: "Unsalted Cheese",
    holdTime: "Anytime, ideally with a meal",
    reps: "30–60g per serving",
    frequency: "Daily or most days",
    howTo: [
      "Choose hard, aged, unsalted varieties: unsalted cottage cheese, ricotta, or fresh mozzarella",
      "Avoid processed cheese slices — look for single-ingredient or minimal-ingredient options",
      "Eat alongside a protein-rich meal for better amino acid synergy",
      "Pair with vitamin K2-rich foods (eggs, fermented foods) to ensure calcium goes to bone, not arteries",
    ],
    tips: [
      "The goal is calcium and quality casein protein — the unsalted requirement avoids unnecessary sodium which causes water retention",
      "Excess sodium causes facial puffiness; unsalted dairy gives you the structural benefits without the bloat",
      "Casein is slow-digesting — eating before sleep supports overnight muscle and bone recovery",
    ],
  },
};

/**
 * Get exercise guide by ID
 */
export function getExerciseGuide(exerciseId: string): ExerciseGuide | null {
  return EXERCISE_GUIDES[exerciseId] ?? null;
}
